---
- name: Get vector distrib
  become: true
  ansible.builtin.get_url:
    # yamllint disable-line rule:line-length
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest:
      "./vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
      # yamllint disable-line rule:comments
    #--------------------------------------
- name: Untar Archive and Create dirs
  become: true
  shell: |
    mkdir {{ vector_dir }}
    mkdir {{ vector_sys_dir }}
    mkdir {{ data_dir }}
    chown root:root {{ vector_sys_dir }} {{ data_dir }}
    tar -xzf vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz -C {{ vector_dir }}
      # yamllint disable-line rule:comments
      #--------------------------------------
- name: Create systemd Unit
  become: true
  template:
    src: ./teamplates/vector_unit.j2
    dest: /etc/systemd/system/vector.service
    owner: root
    group: root
# yamllint disable-line rule:comments
#--------------------------------------
- name: Copy  bin file
  become: true
  shell: |
    cp -av {{ vector_dir }}/vector-x86_64-unknown-linux-musl/bin/vector /usr/bin/
    chown root:root /etc/systemd/system/vector.service
    chown root:root /usr/bin/vector
    systemctl daemon-reload
- name: Sleep for 15 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 15
  delegate_to: localhost
# yamllint disable-line rule:comments
#--------------------------------------
- name: Push a new vector.yaml config file
  become: true
  template:
    src: ./teamplates/vector_conf.j2
    dest: "{{ vector_sys_dir }}/vector.yaml"
    backup: yes
    owner: root
    group: root
  notify:
    - Restart vector
# yamllint disable-line rule:comments
#--------------------------------------
- name: Ensure vector is running
  become: true
  ansible.builtin.service:
    name: vector
    state: started
# yamllint disable-line rule:comments
#--------------------------------------
